source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "GT6TuneAssistant" do

end

target "GT6TuneAssistantTests" do

end
